### ISSUE TITLE
Jumps between breaks and Pomodoros

### ISSUE THREAD

**Issue by ScalyDragon** [benjamonnguyen/Pomomo#1]
![Bildschirmfoto 2021-05-04 um 19 15 21](https://user-images.githubusercontent.com/18486085/117043306-578d7300-ad0d-11eb-877c-98f0e3819def.png)

**Comment by benjamonnguyen** [comment]
I am aware of the issue and will begin working on it today!

**Comment by benjamonnguyen** [comment]
Changes have been pushed. I will monitor for the error for now.

**Comment by benjamonnguyen** [comment]
Has not happened in 2 weeks. Seems to be resolved...
