### ISSUE TITLE
Times out somtimes

### ISSUE THREAD

**Issue by ShaneHeldsinger** [benjamonnguyen/Pomomo#2]
I have tried to use the bot with these settings: pom!start 25 5 20 4
When I was at the long break after 20 min the bot did nothing. I tried to send a command to it and was not responding.

Later I tried using it again and after the first Pomodoro more than 25 minutes passed and the bot did nothing. After 2 minutes of trying to get a response, the bot finally responded.

Below is a screenshot of the chat

![Pomo Bug](https://user-images.githubusercontent.com/41893689/118551782-5ffa9a80-b75e-11eb-98df-055894ea65d3.png)

**Comment by benjamonnguyen** [comment]
Thanks for the report! I am aware of this issue and am working on figuring out this await async stuff

**Comment by benjamonnguyen** [comment]
Fixed deadlocking issue!
